/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.teste.uteis;

import com.k33ptoo.components.KButton;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author NOTE
 */
public class ComponentPopup extends javax.swing.JFrame {

    /**
     * Creates new form ComponentPopup
     */
    public ComponentPopup() {
        initComponents();

        aplicarEstilosPopup();

    }

    private void estilizarLabelPopup(JLabel label, String texto) {
        // Formata o texto com HTML, adicionando margens e quebras de linha
        label.setText("<html><body style='text-align: center; padding: 10px; width: 280px;'>" + texto.replaceAll("\n", "<br>") + "</body></html>");

        label.setForeground(new Color(26, 131, 43)); // Texto branco
        //label.setBackground(new Color(26, 131, 43));  Cor de fundo verde
        label.setOpaque(true); // Torna o fundo da label opaco para exibir a cor de fundo
        label.setHorizontalAlignment(SwingConstants.CENTER); // Centraliza horizontalmente
        label.setVerticalAlignment(SwingConstants.CENTER); // Centraliza verticalmente
        label.setFont(new Font("Roboto", Font.BOLD, 16)); // Define a fonte
        label.setPreferredSize(new Dimension(300, 60)); // Ajuste de tamanho conforme necessário
    }

    private void estilizarBotoesPopup(KButton btn, String nome, Color corFundo, Color corHover) {
        btn.setPreferredSize(new Dimension(150, 50)); // Tamanho ajustado para o popup
        btn.setLayout(new BorderLayout()); // Layout para centralizar o texto no botão

        // Configura o texto do botão
        JLabel textLabel = new JLabel(nome);
        textLabel.setForeground(Color.WHITE); // Texto em branco
        textLabel.setFont(new Font("Roboto", Font.BOLD, 14)); // Fonte e tamanho

        // Painel para o texto
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS)); // Alinhamento horizontal no painel
        panel.setOpaque(false); // Transparente para não afetar a cor do botão

        // Adiciona o texto ao painel
        panel.add(textLabel);
        btn.add(panel, BorderLayout.CENTER); // Adiciona o painel centralizado no botão

        // Configurações de estilo
        btn.setkBackGroundColor(corFundo); // Cor de fundo principal
        btn.setkHoverColor(corHover); // Cor de hover
        btn.setkForeGround(Color.WHITE); // Texto em branco
        btn.setBorderPainted(false);
        btn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // Efeito de hover personalizado
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setkBackGroundColor(corHover); // Cor de fundo ao passar o mouse
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setkBackGroundColor(corFundo); // Cor padrão ao sair
            }
        });
    }

// Chame a função de estilização para cada botão, passando a cor de fundo e a cor de hover desejadas
    private void aplicarEstilosPopup() {
        // Estiliza os botões
        estilizarBotoesPopup(btnPopup1, "", new Color(26, 131, 43), new Color(52, 153, 68));
        estilizarBotoesPopup(btnPopup2, "", new Color(204, 51, 51), new Color(255, 102, 102));

        // Estiliza a labelPopup
        estilizarLabelPopup(labelPopup, "Mensagem de Confirmação"); // Exemplo de texto para a label
    }

    // Método para setar o texto da label
    public void setLabelText(String texto) {
        labelPopup.setText(texto);
    }

// Métodos para configurar os textos dos botões
    public void setButton1Text(String texto) {
        btnPopup1.setText(texto);
    }

    public void setButton2Text(String texto) {
        btnPopup2.setText(texto);
    }

// Método para adicionar o listener de ação aos botões
    public void addButtonActionListener(ActionListener listener) {
        btnPopup1.addActionListener(listener);
        btnPopup2.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPopup = new javax.swing.JLabel();
        btnPopup1 = new com.k33ptoo.components.KButton();
        btnPopup2 = new com.k33ptoo.components.KButton();

        setTitle("Mensagem");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));

        labelPopup.setText("jLabel1");

        btnPopup1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPopup1.setkAllowGradient(false);
        btnPopup1.setkBackGroundColor(new java.awt.Color(26, 131, 43));
        btnPopup1.setkHoverColor(new java.awt.Color(52, 153, 68));
        btnPopup1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPopup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopup1ActionPerformed(evt);
            }
        });

        btnPopup2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPopup2.setkAllowGradient(false);
        btnPopup2.setkBackGroundColor(new java.awt.Color(26, 131, 43));
        btnPopup2.setkHoverColor(new java.awt.Color(52, 153, 68));
        btnPopup2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPopup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopup2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnPopup1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPopup2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPopup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelPopup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPopup1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPopup2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPopup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPopup1ActionPerformed

    private void btnPopup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPopup2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComponentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComponentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComponentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComponentPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComponentPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnPopup1;
    private com.k33ptoo.components.KButton btnPopup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPopup;
    // End of variables declaration//GEN-END:variables
}
